import{a as L,S,i as p}from"./assets/vendor-eded45c0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function g(r){return r.map(({webformatURL:s,largeImageURL:a,tags:l,likes:e,views:t,comments:c,downloads:b})=>`
    <li class="gallery-card">
        <a class="card-link" href="${a}">
            <img class="image" src="${s}" alt="${l}"></a>
        <ul class="card-description">
            <li><p class="name">Likes</p>
            <p class="value">${e}</p></liss=>
            <li><p class="name">Views</p>
            <p class="value">${t}</p></li>
            <li><p class="name">Comments</p>
            <p class="value">${c}</p></li>
            <li><p class="name">Downloads</p>
            <p class="value">${b}</p></li>
        </ul>
    </li>
    `).join("")}function m(r,s){const a="https://pixabay.com/api/",l="43226276-a07a0c17e428cfffb021b9b05",e=new URLSearchParams({key:l,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s});return L.get(`${a}?${e.toString()}`).then(t=>{if(!t.data)throw new Error(t.status);return t.data}).catch(t=>{throw new Error("Request failed with status:"+t.response.status)})}const n=document.querySelector(".form"),w=document.querySelector(".input");let d;const o=document.querySelector(".loader");o.style.display="none";const f=document.querySelector(".gallery"),i=document.querySelector(".load-button");i.style.display="none";const u=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});let y=1;const h=15;n.addEventListener("submit",P);i.addEventListener("click",v);async function P(r){if(r.preventDefault(),d=w.value.trim(),o.style.display="block",i.style.display="none",f.innerHTML="",d===""){o.style.display="none",i.style.display="none",n.reset(),p.info({message:"Looks like you forgot to fill in the search query...",position:"topRight"});return}try{const s=await m(d,y);o.style.display="none",s.totalHits===0?(n.reset(),p.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})):s.totalHits<=h?(f.insertAdjacentHTML("beforeend",g(s.hits)),i.style.display="none",u.refresh(),n.reset()):(f.insertAdjacentHTML("beforeend",g(s.hits)),i.style.display="block",u.refresh(),n.reset())}catch{o.style.display="none",u.refresh(),n.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}async function v(r){r.preventDefault(),y++,o.style.display="block";try{const s=await m(d,y),a=Math.ceil(s.totalHits/h);f.insertAdjacentHTML("beforeend",g(s.hits)),u.refresh(),o.style.display="none",y===a&&(i.style.display="none",p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{o.style.display="none",u.refresh(),n.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}
//# sourceMappingURL=commonHelpers.js.map
