import{a as L,S,i as p}from"./assets/vendor-eded45c0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function g(r){return r.map(({webformatURL:t,largeImageURL:a,tags:n,likes:e,views:s,comments:c,downloads:b})=>`
    <li class="gallery-card">
        <a class="card-link" href="${a}">
            <img class="image" src="${t}" alt="${n}"></a>
        <ul class="card-description">
            <li><p class="name">Likes</p>
            <p class="value">${e}</p></liss=>
            <li><p class="name">Views</p>
            <p class="value">${s}</p></li>
            <li><p class="name">Comments</p>
            <p class="value">${c}</p></li>
            <li><p class="name">Downloads</p>
            <p class="value">${b}</p></li>
        </ul>
    </li>
    `).join("")}async function m(r,t){const a="https://pixabay.com/api/",n="43226276-a07a0c17e428cfffb021b9b05",e=new URLSearchParams({key:n,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});try{return(await L.get(`${a}?${e.toString()}`)).data}catch(s){throw new Error("Request failed with status:"+s.response.status)}}const i=document.querySelector(".form"),w=document.querySelector(".input");let y;const o=document.querySelector(".loader");o.style.display="none";const f=document.querySelector(".gallery"),l=document.querySelector(".load-button");l.style.display="none";const u=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});let d=1;const h=15;i.addEventListener("submit",P);l.addEventListener("click",v);async function P(r){if(r.preventDefault(),y=w.value.trim(),o.style.display="block",l.style.display="none",f.innerHTML="",d=1,y===""){o.style.display="none",l.style.display="none",i.reset(),p.info({message:"Looks like you forgot to fill in the search query...",position:"topRight"});return}try{const t=await m(y,d);o.style.display="none",t.totalHits===0?(i.reset(),p.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})):t.totalHits<=h?(f.insertAdjacentHTML("beforeend",g(t.hits)),l.style.display="none",u.refresh(),i.reset()):(f.insertAdjacentHTML("beforeend",g(t.hits)),l.style.display="block",u.refresh(),i.reset())}catch{o.style.display="none",u.refresh(),i.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}async function v(r){r.preventDefault(),d++,o.style.display="block";try{const t=await m(y,d),a=Math.ceil(t.totalHits/h);f.insertAdjacentHTML("beforeend",g(t.hits));const e=document.querySelector(".gallery-card").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),u.refresh(),o.style.display="none",d===a&&(l.style.display="none",p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{o.style.display="none",u.refresh(),i.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}
//# sourceMappingURL=commonHelpers.js.map
