import{a as L,S,i as p}from"./assets/vendor-eded45c0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function g(r){return r.map(({webformatURL:t,largeImageURL:a,tags:l,likes:e,views:s,comments:c,downloads:b})=>`
    <li class="gallery-card">
        <a class="card-link" href="${a}">
            <img class="image" src="${t}" alt="${l}"></a>
        <ul class="card-description">
            <li><p class="name">Likes</p>
            <p class="value">${e}</p></liss=>
            <li><p class="name">Views</p>
            <p class="value">${s}</p></li>
            <li><p class="name">Comments</p>
            <p class="value">${c}</p></li>
            <li><p class="name">Downloads</p>
            <p class="value">${b}</p></li>
        </ul>
    </li>
    `).join("")}function m(r){const t="https://pixabay.com/api/",a="43226276-a07a0c17e428cfffb021b9b05",l=new URLSearchParams({key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15});return L.get(`${t}?${l.toString()}`).then(e=>{if(!e.data)throw new Error(e.status);return e.data}).catch(e=>{throw new Error("Request failed with status:"+e.response.status)})}const n=document.querySelector(".form"),w=document.querySelector(".input");let u;const o=document.querySelector(".loader");o.style.display="none";const d=document.querySelector(".gallery"),i=document.querySelector(".load-button");i.style.display="none";const y=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});let f=1;const h=15;n.addEventListener("submit",P);i.addEventListener("click",v);async function P(r){if(r.preventDefault(),u=w.value.trim(),o.style.display="block",i.style.display="none",d.innerHTML="",u===""){o.style.display="none",i.style.display="none",n.reset(),p.info({message:"Looks like you forgot to fill in the search query...",position:"topRight"});return}try{const t=await m(u);o.style.display="none",t.totalHits===0?(n.reset(),p.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})):t.totalHits<=h?(d.insertAdjacentHTML("beforeend",g(t.hits)),i.style.display="none",y.refresh(),n.reset()):(d.insertAdjacentHTML("beforeend",g(t.hits)),i.style.display="block",y.refresh(),n.reset())}catch{o.style.display="none",y.refresh(),n.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}async function v(r){r.preventDefault(),f++,o.style.display="block";try{const t=await m(u,f),a=Math.ceil(t.totalHits/h);d.insertAdjacentHTML("beforeend",g(t.hits)),o.style.display="none",f===a&&(i.style.display="none",p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{o.style.display="none",y.refresh(),n.reset(),p.error({message:"Oops! Something went wrong... Please, try again!",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}}
//# sourceMappingURL=commonHelpers.js.map
